# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oplus/sm8350-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter cupid ice lunaa martini porsche,$(TARGET_DEVICE)),)

endif
